### ISSUE TITLE
[Extra Metadata Loader] Neither Logos Or Videos Are Downloading From Steam

### ISSUE THREAD

**Issue by RetroFlock** [darklinkpower/PlayniteExtensionsCollection#684]
### Extension name

Extra Metadata Loader

### Bug Description

Whenever I try to download logos/videos from Steam using this extension, it never works, even though the games do have logos/videos on their pages.

### Logs

[playnite.log](https://github.com/user-attachments/files/22631570/playnite.log)

[extensions.log](https://github.com/user-attachments/files/22631572/extensions.log)

**Comment by darklinkpower** [comment]
I've release a new version that should fix it but if it doesn't, please share examples of games having this issue, including which library they belong to and any information that could be useful.

**Comment by RetroFlock** [comment]
It's still happening. Here's a video of a game, Pulmo, that I got on Steam recently. It has a logo and video on its Steam page, but, as the 2 videos show, nothing downloads. 

https://github.com/user-attachments/assets/4493e7e1-60a2-4953-baeb-6140b2c77375
https://github.com/user-attachments/assets/488f9fb9-dcf8-4102-8810-c69378fed43e

**Comment by darklinkpower** [comment]
> [@darklinkpower](https://github.com/darklinkpower)

It's not needed to tag me in a separate message, I get notified on here and get an email for any activity.

I just tried it with this game and see this:

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   en System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   en FlowHttp.Requests.FlowHttpFileRequest.<DownloadFileAsync>d__6.MoveNext() en C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\FlowHttp\HttpRequests\FlowHttpFileRequest.cs:línea 113
03-10 21:00:05.689|DEBUG|ExtraMetadataLoader#VideosDownloader:DownloadSteamVideo starting for game Pulmo
03-10 21:00:05.949|DEBUG|ExtraMetadataLoader#SteamWeb:Obtained 1 games from Steam search term Pulmo
03-10 21:00:06.241|ERROR|ExtraMetadataLoader#FlowHttpRequestBase`1:Download failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   en System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   en FlowHttp.Requests.FlowHttpFileRequest.<DownloadFileAsync>d__6.MoveNext() en C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\FlowHttp\HttpRequests\FlowHttpFileRequest.cs:línea 113
```

So I looked into the data source:

https://store.steampowered.com/api/appdetails?appids=3752540

<img width="1187" height="313" alt="Image" src="https://github.com/user-attachments/assets/b1e9d5fc-6a55-46da-9c90-1d19eb284862" />

And could verify that the files are not found in these addresses, despite the data having them:

https://video.akamai.steamstatic.com/store_trailers/257207498/movie480.mp4?t=1758991974

https://video.akamai.steamstatic.com/store_trailers/257207498/movie_max.mp4?t=1758991974

<img width="399" height="118" alt="Image" src="https://github.com/user-attachments/assets/565b61e9-5bc4-400f-8173-0c1c8e53b042" />

I'm wondering if this a rare error, or perhaps Steam plans to delete all videos and only leave the playlist in working state:

<img width="1170" height="538" alt="Image" src="https://github.com/user-attachments/assets/99334cff-e9a7-45ab-84ff-3deebe6dbe06" />

In such case it will be needed to see how support can be added for those.

**Comment by RetroFlock** [comment]
So what can I do in the meantime?

**Comment by Goeny** [comment]
Same issue here.

**Comment by LexFH** [comment]
Same issue for all games added since 18/10/2025

**Comment by darklinkpower** [comment]
> Hello, for me version 1.83 fixes the problem for most games, but not all. For example "MARVEL Cosmic Invasion" or "Samurai Academy: Paws of Fury" do not get a video.

I just tried with that game and I can't reproduce it:

<img width="936" height="640" alt="Image" src="https://github.com/user-attachments/assets/d33299b4-fdc8-424e-b272-ba0cd2cacbe3" />

Just to be sure, is the issue when trying to download the video (from right click menu) or when streaming on demand? Because if it's the latter unfortunately it won't be reliable from now on so downloading it's recommended, at least until I can work on changing the video player the extension uses to one that can stream

**Comment by RetroFlock** [comment]
The logo problem has come back again. Any ideas?
